### ISSUE TITLE
행사 일정 - Session

### ISSUE THREAD

**Issue by BurningDroid** [goldforestdev/HPPK-TOCTW#1]
행사 일정을 보여주는 UI
  - [ ] List view
  - [ ] Details view

## 행사 일정표 저장소
* Firebase - Firestore

## Session class
```kotlin
title: String
startTime: Long
endTime: Long
location: String
description: String
photoUrls: List<String>
videoUrls: List<String>
staff members: List<Staff>
category: List<Category>
```

**Comment by BurningDroid** [comment]
@hyeongjudev 
Booth 클래스에 stamp 찍어주는 booth인지 여부 나타내는 boolean 값도 하나 추가해주세요~

**Comment by BurningDroid** [comment]
@hyeongjudev 
Booth의 상태에 "종료" 상태도 추가해주세요
> 다만 피치못해 재료가 다 떨어지거나 문제가 생기면, 앱에서 Closed 처리 등도 되면 좋을 것 같습니다.
(붐비는 것 표시 기능에 Closed 도 추가 ?)

**Comment by hyeongjudev** [comment]
@yoonhok524 추가 했어요.

**Comment by BurningDroid** [comment]
@hyeongjudev
Booth 클래스에 stamp 찍어주는 booth인지 여부 나타내는 boolean 값도 하나 추가해주세요~

**Comment by BurningDroid** [comment]
@hyeongjudev 
stamp 찍어주는 booth 여부는 제가 추가할게요~

**Comment by hyeongjudev** [comment]
@hyeongjudev 필터 정보를 위해 floor 데이터 추가 해주세요~

**Comment by hyeongjudev** [comment]
@hyeongjudev 네 알겠습니다.(이상한 사람 같군요;;)
