### ISSUE TITLE
Schedule data module

### ISSUE THREAD

**Issue by BurningDroid** [goldforestdev/HPPK-TOCTW#8]
schedule 정보를 Firestore에서 가져오기 위해 사용할 모듈
 - Scheduler 클래스 정의
 - Repository
 - DataSource

**Comment by BurningDroid** [comment]
일정을 Schedule로 할지, booth로 할지, session으로 할지는... 좀더 고민이 필요하겠어요

**Comment by hyeongjudev** [comment]
@yoonhok524 일정표와 작년 행사를 생각 했을때 Booth나 Session이 맞을 듯 해요.
몇시 부터 몇시까지 정해진 시간은 따로 없는 듯 해요.

**Comment by BurningDroid** [comment]
@hyeongjudev 네, 시간은 일단 최종 릴리즈 전에 요청해서 받도록 하고
시간이 없는 건 일단 행사 시작 ~ 행사 종료까지로 잡으면 될 것 같다란 생각이...
