### ISSUE TITLE
stamp 찍은 상태에서 child 삭제 안되는 문제

### ISSUE THREAD

**Issue by BurningDroid** [goldforestdev/HPPK-TOCTW#80]

**Comment by yoonhok524** [comment]
fix - https://github.com/goldforestdev/HPPK-TOCTW/commit/7e7d9231cec343592dea1b2d9d5893f0d83c0789

**Comment by BurningDroid** [comment]
fix - https://github.com/goldforestdev/HPPK-TOCTW/pull/81
